/* Framework imports ----------------------------------- */
import React from 'react';

/* Module imports -------------------------------------- */
import { Inter } from 'next/font/google';

/* Component imports ----------------------------------- */

/* Style imports --------------------------------------- */
import './globals.css';
import Copyright from 'components/Copyright/Copyright';

/* Type imports ---------------------------------------- */

/* External variables ---------------------------------- */
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: [ 'latin' ]});

/* RootLayout component prop types --------------------- */
interface RootLayoutProps {
  children: React.ReactNode;
}

/* RootLayout component -------------------------------- */
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </main>
        <footer>
          <Copyright />
        </footer>
      </body>
    </html>
  );
};

/* Export RootLayout component ------------------------- */
export default RootLayout;
