'use client';

/* Framework imports ----------------------------------- */
import React from 'react';

/* Module imports -------------------------------------- */

/* Component imports ----------------------------------- */
import ThemeRegistry from 'components/Theme/ThemeRegistry/ThemeRegistry';

/* Style imports --------------------------------------- */
import './globals.css';
import Copyright from 'components/Copyright/Copyright';

/* Type imports ---------------------------------------- */

/* External variables ---------------------------------- */
const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/* RootLayout component prop types --------------------- */
interface RootLayoutProps {
  children: React.ReactNode;
}

/* RootLayout component -------------------------------- */
const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <title>
          {metadata.title}
        </title>
        <meta
          name="description"
          content={metadata.description}
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </head>
      <ThemeRegistry>
        <body className="flex flex-col min-h-screen">
          <header className="flex-0 z-10 w-screen items-center justify-between font-mono text-sm flex flex-col lg:flex-row lg:px-24 lg:py-8">
            <p className="left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 p-2 lg:dark:bg-zinc-800/30">
              Liste des événements de la fête de la musique à Bordeaux
            </p>
            <div className="invisible lg:visible fixed left-0 flex h-48 w-full justify-center from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none">
              <a
                className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
                href="https://github.com/Clovel"
                target="_blank"
                rel="noopener noreferrer"
              >
                By Clovis Durand
              </a>
            </div>
          </header>
          <main className="flex-1 min-h-full flex flex-col items-center lg:p-24">
            {children}
          </main>
          <footer
            className="flex flex-col justify-center"
            style={{ height: 54 }}
          >
            <Copyright />
          </footer>
        </body>
      </ThemeRegistry>
    </html>
  );
};

/* Export RootLayout component ------------------------- */
export default RootLayout;
